//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AteraDevProject.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Devices
    {
        public int DeviceId { get; set; }
        public string Name { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Owners Owners { get; set; }
    }
}
